remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
title: Flower Recognition App
description: An image classification application that classifies 10 different types of Bengali Flowers

author: 
name: Nahid Akhtar